### ISSUE TITLE
Aquire the PineTime dev kit

### ISSUE THREAD

**Issue by Slurre** [Slurre/PES-Project#1]
- [ ] Verify that we are allowed to buy the dev kit
- [ ] Order it
- [ ] Pick it up
- [ ] Start flashing it

**Comment by ialokim** [comment]
> * Order it
> * Pick it up

Note that delivery to Sweden might take around 1 month.

**Comment by ialokim** [comment]
And it is actually currently out of stock, unfortunately: https://pine64.com/product/pinetime-smartwatch-dev-kit-sealed-twin/
