### ISSUE TITLE
Determine format of presentation

### ISSUE THREAD

**Issue by Slurre** [Slurre/PES-Project#4]
How are we supposed to present?

**Comment by ialokim** [comment]
Unfortunately I won't be available on March, 31st. Perhaps we can ask to present a day before?

**Comment by ialokim** [comment]
> How are we supposed to present?

I think we need to write a 2-5 (?) page project proposition.

**Comment by ialokim** [comment]
see also https://uppsala.instructure.com/courses/45926/files?preview=3149376
